name: CI/CD Innovatech

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar backend despacho
        run: |
          cd back-bespachos-springboot/api-rest-despacho
          ./mvnw clean package -DskipTests

      - name: Compilar backend ventas
        run: |
          cd back-ventas-springboot/api-rest-ventas
          mvn clean package -DskipTests

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Compilar frontend
        run: |
          cd front-despacho
          npm ci
          npm run build

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y push imagen frontend
        run: |
          docker build -t 806943087941.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:latest ./front-despacho
          docker push 806943087941.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:latest

      - name: Build y push imagen despacho
        run: |
          docker build -t 806943087941.dkr.ecr.us-east-1.amazonaws.com/innovatech-despacho:latest ./back-bespachos-springboot/api-rest-despacho
          docker push 806943087941.dkr.ecr.us-east-1.amazonaws.com/innovatech-despacho:latest

      - name: Build y push imagen ventas
        run: |
          docker build -t 806943087941.dkr.ecr.us-east-1.amazonaws.com/innovatech-ventas:latest ./back-ventas-springboot/api-rest-ventas
          docker push 806943087941.dkr.ecr.us-east-1.amazonaws.com/innovatech-ventas:latest

      - name: Despliegue Kubernetes
        run: |
          echo "Deploy preparado con manifiestos Kubernetes en carpeta k8s/"
          echo "kubectl apply -f k8s/"
